name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release UM Core
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Build app
        run: npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
